# Background image of the landing page
background: /images/site/background.png

# Provide logos for your site. The inverted logo will be used in the initial
# transparent navbar and the main logo will be used in the non-transparent navbar.
logo:
  main: /images/site/main-logo.png
  inverted: /images/site/inverted-logo.png
  favicon: /images/site/favicon.png

# GitHub repo of your site
gitRepo: https://github.com/JaceTheBlu/GGestin.com
# Default branch of your Git repo
gitBranch: main

topNavbar:
  maxVisibleSections: 7

# Provide footer configuration.
footer:
  enable: true
  
  # You can provide your custom footer template using this option.
  # Put your template in "layouts/partials" folder of your repo.
  template: footer.html
  
  # Show/hide navigation in the footer. Default is "true".
  navigation:
    enable: false
    # show custom menus in the footer
    customMenus: false

  # Show/hide "Contact Me" section in the footer. Default is "true".
  contactMe:
    enable: true
  
  # Show/hide credentials section in the footer. Default is "true".
  credentials:
    enable: false

  newsletter:
    enable: false
  
  # Show/hide disclaimer notice in the footer. Default is "false".
  disclaimer:
    enable: false
